"""
Defines the data structures for optimization recommendations.
"""
from pydantic import BaseModel, Field
from typing import List

class OptimizationRecommendation(BaseModel):
    """Describes a single recommended optimization strategy."""
    strategy_name: str = Field(..., description="Name of the strategy (e.g., 'TFLite Full INT8 Quantization', 'FP16 Quantization').")
    estimated_ram_kb: float = Field(..., description="Estimated RAM usage in KB.")
    estimated_rom_kb: float = Field(..., description="Estimated Flash/ROM usage in KB.")
    priority_score: float = Field(..., description="Score from 0.0 to 1.0 indicating the suitability of the strategy.")
    summary: str = Field(..., description="Summary of the recommendation, its pros, cons, and feasibility.")

class AdvisorReport(BaseModel):
    """
    Complete report generated by the Advisor Engine, containing one or more recommendations.
    """
    model_sha256: str = Field(..., description="SHA256 hash of the model file for unique identification.")
    target_hardware: str = Field(..., description="Identifier of the target hardware device.")
    recommendations: List[OptimizationRecommendation] = Field(..., description="List of optimization recommendations.")